trigger:
- master

pool: 'Hosted Windows 2019 with VS2019'

steps:
- task: Bash@3
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: ./build.sh
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: NuGetCommand@2
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    packagesToPush: 'artifacts/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org MvxPlugins'