trigger:
  branches:
    include:
    - main
    - develop
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - '**/*.yml'

pr:
  branches:
    include:
    - main
    - develop
    - rel/*
  paths:
    exclude:
    - '**/*.md'
    - '**/*.yml'

pool:
  vmImage: windows-2019

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- powershell: |
    dotnet tool install --tool-path . --version 0.35.0 Cake.Tool
    ./dotnet-cake

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
