# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'Hosted Windows 2019 with VS2019'

steps:
- task: Bash@3
  displayName: 'Run Cake Build'
  inputs:
    targetType: filePath
    filePath: ./build.sh