#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AzureAccessControl.Sample.Droid.Resource", IsApplication=true)]

namespace AzureAccessControl.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Resource.String.mvxplugins_libname = global::AzureAccessControl.Sample.Droid.Resource.String.mvxplugins_libname;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxBind = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxBind;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxDropDownItemTemplate = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxItemTemplate = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxItemTemplate;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxLang = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxLang;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxSource = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxSource;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Attribute.MvxTemplate = global::AzureAccessControl.Sample.Droid.Resource.Attribute.MvxTemplate;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Drawable.mvxplugins_ic_action_refresh = global::AzureAccessControl.Sample.Droid.Resource.Drawable.mvxplugins_ic_action_refresh;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Id.MvxBindingTagUnique = global::AzureAccessControl.Sample.Droid.Resource.Id.MvxBindingTagUnique;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Id.identity_provider_header = global::AzureAccessControl.Sample.Droid.Resource.Id.identity_provider_header;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Id.identity_provider_listview = global::AzureAccessControl.Sample.Droid.Resource.Id.identity_provider_listview;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Id.identity_provider_loggedin = global::AzureAccessControl.Sample.Droid.Resource.Id.identity_provider_loggedin;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Id.mvxplugins_action_relogin = global::AzureAccessControl.Sample.Droid.Resource.Id.mvxplugins_action_relogin;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Layout.identityproviderlistview = global::AzureAccessControl.Sample.Droid.Resource.Layout.identityproviderlistview;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Layout.listitem_identityprovider = global::AzureAccessControl.Sample.Droid.Resource.Layout.listitem_identityprovider;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Menu.login = global::AzureAccessControl.Sample.Droid.Resource.Menu.login;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.String.mvxplugins_action_relogin = global::AzureAccessControl.Sample.Droid.Resource.String.mvxplugins_action_relogin;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.String.mvxplugins_dialog_loading = global::AzureAccessControl.Sample.Droid.Resource.String.mvxplugins_dialog_loading;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxBinding = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxBinding;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxBinding_MvxBind = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxBinding_MvxLang = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxControl = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxControl;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxControl_MvxTemplate = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxImageView = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxImageView;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxImageView_MvxSource = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxListView = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxListView;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Cheesebaron.MvxPlugins.AzureAccessControl.Droid.Views.Resource.Styleable.MvxListView_MvxItemTemplate = global::AzureAccessControl.Sample.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int mvxplugins_ic_action_refresh = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int audience = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int audienceLabel = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int expiresOn = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int expiresOnLabel = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int identityProvider = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int identityProviderLabel = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int identity_provider_header = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int identity_provider_listview = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int identity_provider_loggedin = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int issuer = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int issuerLabel = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int loginButton = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int mvxplugins_action_relogin = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int rawToken = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int rawTokenLabel = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int textView1 = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int identityproviderlistview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listitem_identityprovider = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashScreen = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int login = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int mvxplugins_action_relogin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mvxplugins_dialog_loading = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mvxplugins_libname = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
